# (c) Copyright 2024 Hewlett Packard Enterprise Development L
---
# yamllint disable rule:line-length
name: Test Workflow

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  release:
    types: [published]
  push:
    tags:
      - "v*"


jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Update Target in Delivery Repo
    steps:
      - name: Testing values
        run: |
          echo "Base Ref: ${{ github.event.base_ref }}"
          echo "github.event.base_ref: ${{ github.event.base_ref }}"
          echo "github.event_name: ${{ github.event_name }}"
          echo "github.event.release.target_commitish: ${{ github.event.release.target_commitish }}"

      - name: Check if the release is from the main branch
        id: check_branch
        run: |
          branch_ref=$(jq -r '.release.target_commitish' "$GITHUB_EVENT_PATH")
          echo "Branch: $branch_ref"
          echo "::set-output name=branch::$branch_ref"

      - name: Run build or deploy if on main branch
        if: steps.check_branch.outputs.branch == 'main'
        run: echo "Running job because release was cut on the main branch."

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Update Delivery repo
        run: |
          echo "Hello Babyy Boyy"
